[deploy]
startCommand = "sh -c 'echo ALEMBIC_FILES: && ls alembic/versions/ && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port $PORT'"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
